# VERSION v1
# docker build -t="liulantao/centos7" .
FROM centos:centos7
MAINTAINER Liu Lantao <liulantao@gmail.com>
ENV REFRESHED_AT 2016-08-25
RUN yum install -y epel-release && yum update -y && yum clean all
